--
-- PostgreSQL database dump
--

\restrict WNeWh8RDA3fUwZZAfZQI3zxyhcIuSvgdDO11CwcFefHFhD0mwIlGkIPJM1KTNmW

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: billing; Type: SCHEMA; Schema: -; Owner: sian
--

CREATE SCHEMA billing;


ALTER SCHEMA billing OWNER TO sian;

--
-- Name: carwash_operation; Type: SCHEMA; Schema: -; Owner: sian
--

CREATE SCHEMA carwash_operation;


ALTER SCHEMA carwash_operation OWNER TO sian;

--
-- Name: identity; Type: SCHEMA; Schema: -; Owner: sian
--

CREATE SCHEMA identity;


ALTER SCHEMA identity OWNER TO sian;

--
-- Name: service_catalog; Type: SCHEMA; Schema: -; Owner: sian
--

CREATE SCHEMA service_catalog;


ALTER SCHEMA service_catalog OWNER TO sian;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: idempotency_keys; Type: TABLE; Schema: billing; Owner: sian
--

CREATE TABLE billing.idempotency_keys (
    id integer NOT NULL,
    scope character varying(100) NOT NULL,
    idempotency_key character varying(128) NOT NULL,
    request_hash character varying(128) NOT NULL,
    status character varying(20) DEFAULT 'PROCESSING'::character varying NOT NULL,
    response_payload jsonb,
    http_status integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT billing_idempotency_keys_status_check CHECK (((status)::text = ANY ((ARRAY['PROCESSING'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE billing.idempotency_keys OWNER TO sian;

--
-- Name: idempotency_keys_id_seq; Type: SEQUENCE; Schema: billing; Owner: sian
--

ALTER TABLE billing.idempotency_keys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME billing.idempotency_keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: billing; Owner: sian
--

CREATE TABLE billing.payments (
    id integer NOT NULL,
    ticket_id integer NOT NULL,
    cashier_id integer NOT NULL,
    plate_number character varying(50) NOT NULL,
    payment_metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    subtotal_amount numeric(12,2) NOT NULL,
    payment_status character varying(20) NOT NULL,
    paid_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    payment_method character varying(20) NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    CONSTRAINT chk_payment_method CHECK (((payment_method)::text = ANY ((ARRAY['CASH'::character varying, 'QRIS'::character varying, 'TRANSFER'::character varying, 'CARD'::character varying])::text[]))),
    CONSTRAINT chk_payment_status CHECK (((payment_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'FAILED'::character varying, 'VOID'::character varying])::text[]))),
    CONSTRAINT chk_subtotal_amount_should_positive CHECK ((subtotal_amount >= (0)::numeric)),
    CONSTRAINT chk_total_amount_should_positive CHECK ((total_amount >= (0)::numeric))
);


ALTER TABLE billing.payments OWNER TO sian;

--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: billing; Owner: sian
--

CREATE SEQUENCE billing.transactions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE billing.transactions_id_seq OWNER TO sian;

--
-- Name: transactions_id_seq; Type: SEQUENCE OWNED BY; Schema: billing; Owner: sian
--

ALTER SEQUENCE billing.transactions_id_seq OWNED BY billing.payments.id;


--
-- Name: idempotency_keys; Type: TABLE; Schema: carwash_operation; Owner: sian
--

CREATE TABLE carwash_operation.idempotency_keys (
    id integer NOT NULL,
    scope character varying(100) NOT NULL,
    idempotency_key character varying(128) NOT NULL,
    request_hash character varying(128) NOT NULL,
    status character varying(20) DEFAULT 'PROCESSING'::character varying NOT NULL,
    response_payload jsonb,
    http_status integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT carwash_operation_idempotency_status_check CHECK (((status)::text = ANY ((ARRAY['PROCESSING'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE carwash_operation.idempotency_keys OWNER TO sian;

--
-- Name: idempotency_keys_id_seq; Type: SEQUENCE; Schema: carwash_operation; Owner: sian
--

ALTER TABLE carwash_operation.idempotency_keys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME carwash_operation.idempotency_keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ticket_voids; Type: TABLE; Schema: carwash_operation; Owner: sian
--

CREATE TABLE carwash_operation.ticket_voids (
    id integer NOT NULL,
    ticket_id integer NOT NULL,
    account_id integer NOT NULL,
    reason text NOT NULL,
    void_time timestamp with time zone NOT NULL
);


ALTER TABLE carwash_operation.ticket_voids OWNER TO sian;

--
-- Name: ticket_voids_id_seq; Type: SEQUENCE; Schema: carwash_operation; Owner: sian
--

CREATE SEQUENCE carwash_operation.ticket_voids_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE carwash_operation.ticket_voids_id_seq OWNER TO sian;

--
-- Name: ticket_voids_id_seq; Type: SEQUENCE OWNED BY; Schema: carwash_operation; Owner: sian
--

ALTER SEQUENCE carwash_operation.ticket_voids_id_seq OWNED BY carwash_operation.ticket_voids.id;


--
-- Name: tickets; Type: TABLE; Schema: carwash_operation; Owner: sian
--

CREATE TABLE carwash_operation.tickets (
    id integer NOT NULL,
    service_type_id integer NOT NULL,
    ticket_number character varying(13) NOT NULL,
    service_name_snapshot character varying(100) NOT NULL,
    service_base_price_snapshot numeric(12,2) NOT NULL,
    service_desc_snapshot text NOT NULL,
    entry_time timestamp with time zone NOT NULL,
    status character varying(50) DEFAULT 'in_progress'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_price_should_positive CHECK ((service_base_price_snapshot > (0)::numeric)),
    CONSTRAINT chk_status_should_valid CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'VOID'::character varying, 'PAID'::character varying])::text[])))
);


ALTER TABLE carwash_operation.tickets OWNER TO sian;

--
-- Name: tickets_id_seq; Type: SEQUENCE; Schema: carwash_operation; Owner: sian
--

CREATE SEQUENCE carwash_operation.tickets_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE carwash_operation.tickets_id_seq OWNER TO sian;

--
-- Name: tickets_id_seq; Type: SEQUENCE OWNED BY; Schema: carwash_operation; Owner: sian
--

ALTER SEQUENCE carwash_operation.tickets_id_seq OWNED BY carwash_operation.tickets.id;


--
-- Name: accounts; Type: TABLE; Schema: identity; Owner: sian
--

CREATE TABLE identity.accounts (
    id integer NOT NULL,
    username character varying(50) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash text NOT NULL,
    role character varying(50) NOT NULL,
    failed_login_attempts integer DEFAULT 0 NOT NULL,
    locked_until timestamp with time zone,
    last_login_at timestamp with time zone,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT chk_accounts_role CHECK (((role)::text = ANY ((ARRAY['CASHIER'::character varying, 'ADMIN'::character varying, 'OWNER'::character varying])::text[])))
);


ALTER TABLE identity.accounts OWNER TO sian;

--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: identity; Owner: sian
--

CREATE SEQUENCE identity.accounts_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE identity.accounts_id_seq OWNER TO sian;

--
-- Name: accounts_id_seq; Type: SEQUENCE OWNED BY; Schema: identity; Owner: sian
--

ALTER SEQUENCE identity.accounts_id_seq OWNED BY identity.accounts.id;


--
-- Name: devices; Type: TABLE; Schema: identity; Owner: sian
--

CREATE TABLE identity.devices (
    id integer NOT NULL,
    device_code character varying(64) NOT NULL,
    name character varying(100) NOT NULL,
    location character varying(100),
    is_active boolean DEFAULT true NOT NULL,
    last_seen_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE identity.devices OWNER TO sian;

--
-- Name: devices_id_seq; Type: SEQUENCE; Schema: identity; Owner: sian
--

ALTER TABLE identity.devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME identity.devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: identity; Owner: sian
--

CREATE TABLE identity.refresh_tokens (
    id integer NOT NULL,
    account_id bigint NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    last_used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE identity.refresh_tokens OWNER TO sian;

--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: identity; Owner: sian
--

CREATE SEQUENCE identity.refresh_tokens_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE identity.refresh_tokens_id_seq OWNER TO sian;

--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: identity; Owner: sian
--

ALTER SEQUENCE identity.refresh_tokens_id_seq OWNED BY identity.refresh_tokens.id;


--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: sian
--

CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);


ALTER TABLE public.alembic_version OWNER TO sian;

--
-- Name: service_types; Type: TABLE; Schema: service_catalog; Owner: sian
--

CREATE TABLE service_catalog.service_types (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    price numeric(12,2) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    is_primary boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT chk_money_should_positive CHECK ((price > (0)::numeric))
);


ALTER TABLE service_catalog.service_types OWNER TO sian;

--
-- Name: service_catalog_id_seq; Type: SEQUENCE; Schema: service_catalog; Owner: sian
--

CREATE SEQUENCE service_catalog.service_catalog_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE service_catalog.service_catalog_id_seq OWNER TO sian;

--
-- Name: service_catalog_id_seq; Type: SEQUENCE OWNED BY; Schema: service_catalog; Owner: sian
--

ALTER SEQUENCE service_catalog.service_catalog_id_seq OWNED BY service_catalog.service_types.id;


--
-- Name: payments id; Type: DEFAULT; Schema: billing; Owner: sian
--

ALTER TABLE ONLY billing.payments ALTER COLUMN id SET DEFAULT nextval('billing.transactions_id_seq'::regclass);


--
-- Name: ticket_voids id; Type: DEFAULT; Schema: carwash_operation; Owner: sian
--

ALTER TABLE ONLY carwash_operation.ticket_voids ALTER COLUMN id SET DEFAULT nextval('carwash_operation.ticket_voids_id_seq'::regclass);


--
-- Name: tickets id; Type: DEFAULT; Schema: carwash_operation; Owner: sian
--

ALTER TABLE ONLY carwash_operation.tickets ALTER COLUMN id SET DEFAULT nextval('carwash_operation.tickets_id_seq'::regclass);


--
-- Name: accounts id; Type: DEFAULT; Schema: identity; Owner: sian
--

ALTER TABLE ONLY identity.accounts ALTER COLUMN id SET DEFAULT nextval('identity.accounts_id_seq'::regclass);


--
-- Name: refresh_tokens id; Type: DEFAULT; Schema: identity; Owner: sian
--

ALTER TABLE ONLY identity.refresh_tokens ALTER COLUMN id SET DEFAULT nextval('identity.refresh_tokens_id_seq'::regclass);


--
-- Name: service_types id; Type: DEFAULT; Schema: service_catalog; Owner: sian
--

ALTER TABLE ONLY service_catalog.service_types ALTER COLUMN id SET DEFAULT nextval('service_catalog.service_catalog_id_seq'::regclass);


--
-- Name: idempotency_keys billing_idempotency_keys_scope_key_unique; Type: CONSTRAINT; Schema: billing; Owner: sian
--

ALTER TABLE ONLY billing.idempotency_keys
    ADD CONSTRAINT billing_idempotency_keys_scope_key_unique UNIQUE (scope, idempotency_key);


--
-- Name: idempotency_keys idempotency_keys_pkey; Type: CONSTRAINT; Schema: billing; Owner: sian
--

ALTER TABLE ONLY billing.idempotency_keys
    ADD CONSTRAINT idempotency_keys_pkey PRIMARY KEY (id);


--
-- Name: payments transactions_pkey; Type: CONSTRAINT; Schema: billing; Owner: sian
--

ALTER TABLE ONLY billing.payments
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: idempotency_keys carwash_operation_idempotency_scope_key_unique; Type: CONSTRAINT; Schema: carwash_operation; Owner: sian
--

ALTER TABLE ONLY carwash_operation.idempotency_keys
    ADD CONSTRAINT carwash_operation_idempotency_scope_key_unique UNIQUE (scope, idempotency_key);


--
-- Name: idempotency_keys idempotency_keys_pkey; Type: CONSTRAINT; Schema: carwash_operation; Owner: sian
--

ALTER TABLE ONLY carwash_operation.idempotency_keys
    ADD CONSTRAINT idempotency_keys_pkey PRIMARY KEY (id);


--
-- Name: ticket_voids ticket_voids_pkey; Type: CONSTRAINT; Schema: carwash_operation; Owner: sian
--

ALTER TABLE ONLY carwash_operation.ticket_voids
    ADD CONSTRAINT ticket_voids_pkey PRIMARY KEY (id);


--
-- Name: tickets tickets_pkey; Type: CONSTRAINT; Schema: carwash_operation; Owner: sian
--

ALTER TABLE ONLY carwash_operation.tickets
    ADD CONSTRAINT tickets_pkey PRIMARY KEY (id);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: identity; Owner: sian
--

ALTER TABLE ONLY identity.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: accounts accounts_username_key; Type: CONSTRAINT; Schema: identity; Owner: sian
--

ALTER TABLE ONLY identity.accounts
    ADD CONSTRAINT accounts_username_key UNIQUE (username);


--
-- Name: devices devices_device_code_key; Type: CONSTRAINT; Schema: identity; Owner: sian
--

ALTER TABLE ONLY identity.devices
    ADD CONSTRAINT devices_device_code_key UNIQUE (device_code);


--
-- Name: devices devices_pkey; Type: CONSTRAINT; Schema: identity; Owner: sian
--

ALTER TABLE ONLY identity.devices
    ADD CONSTRAINT devices_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: identity; Owner: sian
--

ALTER TABLE ONLY identity.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: accounts uq_accounts_email; Type: CONSTRAINT; Schema: identity; Owner: sian
--

ALTER TABLE ONLY identity.accounts
    ADD CONSTRAINT uq_accounts_email UNIQUE (email);


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: sian
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: service_types service_catalog_name_key; Type: CONSTRAINT; Schema: service_catalog; Owner: sian
--

ALTER TABLE ONLY service_catalog.service_types
    ADD CONSTRAINT service_catalog_name_key UNIQUE (name);


--
-- Name: service_types service_catalog_pkey; Type: CONSTRAINT; Schema: service_catalog; Owner: sian
--

ALTER TABLE ONLY service_catalog.service_types
    ADD CONSTRAINT service_catalog_pkey PRIMARY KEY (id);


--
-- Name: tickets fk_ticket_service_type; Type: FK CONSTRAINT; Schema: carwash_operation; Owner: sian
--

ALTER TABLE ONLY carwash_operation.tickets
    ADD CONSTRAINT fk_ticket_service_type FOREIGN KEY (service_type_id) REFERENCES service_catalog.service_types(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: ticket_voids ticket_voids_account_id_fkey; Type: FK CONSTRAINT; Schema: carwash_operation; Owner: sian
--

ALTER TABLE ONLY carwash_operation.ticket_voids
    ADD CONSTRAINT ticket_voids_account_id_fkey FOREIGN KEY (account_id) REFERENCES identity.accounts(id);


--
-- Name: ticket_voids ticket_voids_ticket_id_fkey; Type: FK CONSTRAINT; Schema: carwash_operation; Owner: sian
--

ALTER TABLE ONLY carwash_operation.ticket_voids
    ADD CONSTRAINT ticket_voids_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES carwash_operation.tickets(id);


--
-- Name: refresh_tokens fk_refresh_tokens_accounts; Type: FK CONSTRAINT; Schema: identity; Owner: sian
--

ALTER TABLE ONLY identity.refresh_tokens
    ADD CONSTRAINT fk_refresh_tokens_accounts FOREIGN KEY (account_id) REFERENCES identity.accounts(id);


--
-- PostgreSQL database dump complete
--

\unrestrict WNeWh8RDA3fUwZZAfZQI3zxyhcIuSvgdDO11CwcFefHFhD0mwIlGkIPJM1KTNmW

