from typing import Protocol

from app.modules.service_catalog.domain.entities.service_type import ServiceType


class IServiceTypeRepository(Protocol):
    async def find_by_id(self, service_type_id: int) -> ServiceType | None: ...

    async def find_by_name(self, service_name: str) -> ServiceType | None: ...

    async def add(self, service_type: ServiceType) -> ServiceType: ...

    async def save(self, service_type: ServiceType) -> ServiceType: ...

    async def delete(self, service_type: ServiceType) -> ServiceType: ...
