CREATE SCHEMA IF NOT EXISTS billing;

CREATE TABLE IF NOT EXISTS billing.payments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id integer NOT NULL REFERENCES carwash_operation.tickets(id),
    cashier_id integer NOT NULL REFERENCES identity.accounts(id),
    plate_number varchar(12) NOT NULL,
    payment_method varchar(20) NOT NULL,
    payment_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    subtotal_amount numeric(12, 2) NOT NULL,
    total_amount numeric(12, 2) NOT NULL,
    payment_status varchar(20) NOT NULL,
    paid_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT payments_ticket_id_unique UNIQUE (ticket_id),
    CONSTRAINT payments_payment_method_check
        CHECK (payment_method IN ('CASH', 'QRIS', 'CARD')),
    CONSTRAINT payments_payment_status_check
        CHECK (payment_status IN ('PENDING', 'PAID', 'FAILED')),
    CONSTRAINT payments_amounts_non_negative_check
        CHECK (subtotal_amount >= 0 AND total_amount >= 0),
    CONSTRAINT payments_paid_at_status_check
        CHECK (
            (payment_status = 'PAID' AND paid_at IS NOT NULL)
            OR (payment_status <> 'PAID' AND paid_at IS NULL)
        )
);

CREATE INDEX IF NOT EXISTS idx_billing_payments_ticket_id
    ON billing.payments(ticket_id);

CREATE INDEX IF NOT EXISTS idx_billing_payments_cashier_id
    ON billing.payments(cashier_id);

CREATE INDEX IF NOT EXISTS idx_billing_payments_payment_status
    ON billing.payments(payment_status);

CREATE INDEX IF NOT EXISTS idx_billing_payments_created_at
    ON billing.payments(created_at DESC);
