CREATE TABLE IF NOT EXISTS carwash_operation.idempotency_keys (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope varchar(100) NOT NULL,
    idempotency_key varchar(128) NOT NULL,
    request_hash varchar(128) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'PROCESSING',
    response_payload jsonb,
    http_status integer,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT carwash_operation_idempotency_scope_key_unique UNIQUE (scope, idempotency_key),
    CONSTRAINT carwash_operation_idempotency_status_check
        CHECK (status IN ('PROCESSING', 'COMPLETED'))
);

CREATE INDEX IF NOT EXISTS idx_carwash_operation_idempotency_expires_at
    ON carwash_operation.idempotency_keys(expires_at);

