CREATE TABLE IF NOT EXISTS identity.devices (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_code varchar(64) NOT NULL UNIQUE,
    name varchar(100) NOT NULL,
    location varchar(100),
    is_active boolean NOT NULL DEFAULT true,
    last_seen_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_identity_devices_is_active
    ON identity.devices(is_active);

